### ISSUE TITLE
Unable to execute queries against the API

### ISSUE THREAD

**Issue by simonparkinsonbates** [NSW-eTendering/NSW-eTendering-API#2]
Hi There,

I've been pointed to this api by the NSW procurement department as a means to integrate search queries into a service I'm developing.

I have cloned the repo and tried to use the api as documented...

I've tried to execute the php examples provided, and they fail...  When the scripts execute they are getting back html, not json data (as they expect).

The api endpoints in the example php's are:

* http://etr-testing.tenders.nsw.gov.au/?event=public.api.contract.search&ResultsPerPage=999
* http://etr-testing.tenders.nsw.gov.au/?event=public.api.tender.search&ResultsPerPage=99

While the etr-testing.tenders.nsw.gov.au host appears to exist, when I do a GET on these urls I'm getting a 302 and a new location (./?event=public.home&invalidEvent=true) which simply returns html.

In the Git Hub Repo the Readme points to various url's where the api is apparently located.  I've tried to use these urls with the "ResultsPerPage=99" parameter but again, for each of them, I'm getting a 302 response telling me to go to a different resource location (./?event=public.home&invalidEvent=true) which returns html.

The Git Hub Repo mentions a wiki... There is none hosted in the repo (that I can find anyway!)

* What am I missing?  I can execute searches manually in the NSW eTendering.
* Is there some sort of Authentication/Authorisation key or even another parameter in the (header or url) that is required to access the api that needs to be included in the GET so that the NSW eTendering system recognises my GET as an api call?
* Is my assumption about the api urls correct (which I based on the reading of the php)

Cheers

simon@vendorpanel.com.au

**Comment by andrewlorien** [comment]
Hi Simon
Sorry about that - we're testing another branch on etr-testing this week (although in the future that will be the place to test your API calls).  For now, i've set up a temporary server you can use : http://ec2-54-206-18-219.ap-southeast-2.compute.amazonaws.com/
Obviously that won't last forever, but I'll keep it live until the API is permanently available on etr-testing.

**Comment by andrewlorien** [comment]
PS Thanks for being our first user!   
We're very keen to get actual feedback on the resources here (including the as-yet-unfinished Wiki).  Please let us know how you're going and what you need, either by email (I'm andrew.lorien@gruden.com) or by creating an issue here.

**Comment by simonparkinsonbates** [comment]
Hi Andrew,

Thanks for the quick response... The new server looks to be good :-) .  I look forward to reading the wiki to find out more about how I can use the api.  Sorry to inundate you with questions but:
1. What sort of time frames are you looking at until the api hits  version 1?  
2. Will we be be able to paginate the returned data (as well as controlling the result count)?

I'm only in the investigative stage at the moment at the moment put plan to be putting together some preliminary scaffolding soon.

Cheers

simon@vendorpanel.com.au

**Comment by andrewlorien** [comment]
Questions are great!
1.  I'm not sure about the timeline.  It's really up to the guys in Finance, and how the deployment works around other priorities.  But we only expect bug fixes from here, no changes.
2. Pagination is built in - see the links {self, next, previous} at the root level of every search response.

**Comment by andrewlorien** [comment]
The API is now live!
[http://tenders.nsw.gov.au/?event=public.api.contract.search](http://tenders.nsw.gov.au/?event=public.api.contract.search)

**Comment by ghost** [comment]
Awesome... Thx!
